// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	jwt "github.com/lumiforge/sellerproof-backend/internal/jwt"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

// GenerateTokenPair provides a mock function with given fields: userID, email, role, orgID
func (_m *TokenManager) GenerateTokenPair(userID string, email string, role string, orgID string) (string, string, error) {
	ret := _m.Called(userID, email, role, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, string, error)); ok {
		return rf(userID, email, role, orgID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(userID, email, role, orgID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) string); ok {
		r1 = rf(userID, email, role, orgID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string, string, string) error); ok {
		r2 = rf(userID, email, role, orgID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTokenExpiry provides a mock function with given fields: tokenType
func (_m *TokenManager) GetTokenExpiry(tokenType string) time.Duration {
	ret := _m.Called(tokenType)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenExpiry")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(tokenType)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// RefreshAccessToken provides a mock function with given fields: refreshTokenString
func (_m *TokenManager) RefreshAccessToken(refreshTokenString string) (string, error) {
	ret := _m.Called(refreshTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(refreshTokenString)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refreshTokenString)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshTokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *TokenManager) ValidateToken(tokenString string) (*jwt.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwt.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
