// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/video.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateMultipartUploadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileName        string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSizeBytes   int64                  `protobuf:"varint,2,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiateMultipartUploadRequest) Reset() {
	*x = InitiateMultipartUploadRequest{}
	mi := &file_proto_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadRequest) ProtoMessage() {}

func (x *InitiateMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateMultipartUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *InitiateMultipartUploadRequest) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *InitiateMultipartUploadRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type InitiateMultipartUploadResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VideoId               string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UploadId              string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	RecommendedPartSizeMb int32                  `protobuf:"varint,3,opt,name=recommended_part_size_mb,json=recommendedPartSizeMb,proto3" json:"recommended_part_size_mb,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitiateMultipartUploadResponse) Reset() {
	*x = InitiateMultipartUploadResponse{}
	mi := &file_proto_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadResponse) ProtoMessage() {}

func (x *InitiateMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateMultipartUploadResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *InitiateMultipartUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *InitiateMultipartUploadResponse) GetRecommendedPartSizeMb() int32 {
	if x != nil {
		return x.RecommendedPartSizeMb
	}
	return 0
}

type GetPartUploadURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	TotalParts    int32                  `protobuf:"varint,2,opt,name=total_parts,json=totalParts,proto3" json:"total_parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartUploadURLsRequest) Reset() {
	*x = GetPartUploadURLsRequest{}
	mi := &file_proto_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartUploadURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartUploadURLsRequest) ProtoMessage() {}

func (x *GetPartUploadURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartUploadURLsRequest.ProtoReflect.Descriptor instead.
func (*GetPartUploadURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{2}
}

func (x *GetPartUploadURLsRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetPartUploadURLsRequest) GetTotalParts() int32 {
	if x != nil {
		return x.TotalParts
	}
	return 0
}

type GetPartUploadURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartUrls      []string               `protobuf:"bytes,1,rep,name=part_urls,json=partUrls,proto3" json:"part_urls,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartUploadURLsResponse) Reset() {
	*x = GetPartUploadURLsResponse{}
	mi := &file_proto_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartUploadURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartUploadURLsResponse) ProtoMessage() {}

func (x *GetPartUploadURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartUploadURLsResponse.ProtoReflect.Descriptor instead.
func (*GetPartUploadURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{3}
}

func (x *GetPartUploadURLsResponse) GetPartUrls() []string {
	if x != nil {
		return x.PartUrls
	}
	return nil
}

func (x *GetPartUploadURLsResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CompleteMultipartUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Parts         []*CompletedPart       `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadRequest) Reset() {
	*x = CompleteMultipartUploadRequest{}
	mi := &file_proto_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadRequest) ProtoMessage() {}

func (x *CompleteMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteMultipartUploadRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CompleteMultipartUploadRequest) GetParts() []*CompletedPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CompletedPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedPart) Reset() {
	*x = CompletedPart{}
	mi := &file_proto_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedPart) ProtoMessage() {}

func (x *CompletedPart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedPart.ProtoReflect.Descriptor instead.
func (*CompletedPart) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{5}
}

func (x *CompletedPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *CompletedPart) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type CompleteMultipartUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadResponse) Reset() {
	*x = CompleteMultipartUploadResponse{}
	mi := &file_proto_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadResponse) ProtoMessage() {}

func (x *CompleteMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteMultipartUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompleteMultipartUploadResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_proto_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResponse) Reset() {
	*x = GetVideoResponse{}
	mi := &file_proto_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResponse) ProtoMessage() {}

func (x *GetVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{8}
}

func (x *GetVideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type SearchVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosRequest) Reset() {
	*x = SearchVideosRequest{}
	mi := &file_proto_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosRequest) ProtoMessage() {}

func (x *SearchVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosRequest.ProtoReflect.Descriptor instead.
func (*SearchVideosRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{9}
}

func (x *SearchVideosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchVideosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchVideosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchVideosResponse) Reset() {
	*x = SearchVideosResponse{}
	mi := &file_proto_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVideosResponse) ProtoMessage() {}

func (x *SearchVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVideosResponse.ProtoReflect.Descriptor instead.
func (*SearchVideosResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{10}
}

func (x *SearchVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *SearchVideosResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Video struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	FileName        string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSizeBytes   int64                  `protobuf:"varint,3,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	UploadStatus    string                 `protobuf:"bytes,5,opt,name=upload_status,json=uploadStatus,proto3" json:"upload_status,omitempty"`
	UploadedAt      int64                  `protobuf:"varint,6,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_video_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{11}
}

func (x *Video) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Video) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Video) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *Video) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Video) GetUploadStatus() string {
	if x != nil {
		return x.UploadStatus
	}
	return ""
}

func (x *Video) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

type CreateShareLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ExpiresInHours int32                  `protobuf:"varint,2,opt,name=expires_in_hours,json=expiresInHours,proto3" json:"expires_in_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShareLinkRequest) Reset() {
	*x = CreateShareLinkRequest{}
	mi := &file_proto_video_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareLinkRequest) ProtoMessage() {}

func (x *CreateShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{12}
}

func (x *CreateShareLinkRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CreateShareLinkRequest) GetExpiresInHours() int32 {
	if x != nil {
		return x.ExpiresInHours
	}
	return 0
}

type CreateShareLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareUrl      string                 `protobuf:"bytes,1,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareLinkResponse) Reset() {
	*x = CreateShareLinkResponse{}
	mi := &file_proto_video_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareLinkResponse) ProtoMessage() {}

func (x *CreateShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{13}
}

func (x *CreateShareLinkResponse) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *CreateShareLinkResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetPublicVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareToken    string                 `protobuf:"bytes,1,opt,name=share_token,json=shareToken,proto3" json:"share_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicVideoRequest) Reset() {
	*x = GetPublicVideoRequest{}
	mi := &file_proto_video_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicVideoRequest) ProtoMessage() {}

func (x *GetPublicVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicVideoRequest.ProtoReflect.Descriptor instead.
func (*GetPublicVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{14}
}

func (x *GetPublicVideoRequest) GetShareToken() string {
	if x != nil {
		return x.ShareToken
	}
	return ""
}

type GetPublicVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicVideoResponse) Reset() {
	*x = GetPublicVideoResponse{}
	mi := &file_proto_video_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicVideoResponse) ProtoMessage() {}

func (x *GetPublicVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicVideoResponse.ProtoReflect.Descriptor instead.
func (*GetPublicVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{15}
}

func (x *GetPublicVideoResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetPublicVideoResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetPublicVideoResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetPublicVideoResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RevokeShareLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeShareLinkRequest) Reset() {
	*x = RevokeShareLinkRequest{}
	mi := &file_proto_video_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeShareLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeShareLinkRequest) ProtoMessage() {}

func (x *RevokeShareLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeShareLinkRequest.ProtoReflect.Descriptor instead.
func (*RevokeShareLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeShareLinkRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type RevokeShareLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeShareLinkResponse) Reset() {
	*x = RevokeShareLinkResponse{}
	mi := &file_proto_video_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeShareLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeShareLinkResponse) ProtoMessage() {}

func (x *RevokeShareLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeShareLinkResponse.ProtoReflect.Descriptor instead.
func (*RevokeShareLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeShareLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_video_proto protoreflect.FileDescriptor

const file_proto_video_proto_rawDesc = "" +
	"\n" +
	"\x11proto/video.proto\x12\x05video\"\x90\x01\n" +
	"\x1eInitiateMultipartUploadRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12&\n" +
	"\x0ffile_size_bytes\x18\x02 \x01(\x03R\rfileSizeBytes\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\"\x92\x01\n" +
	"\x1fInitiateMultipartUploadResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\x127\n" +
	"\x18recommended_part_size_mb\x18\x03 \x01(\x05R\x15recommendedPartSizeMb\"V\n" +
	"\x18GetPartUploadURLsRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1f\n" +
	"\vtotal_parts\x18\x02 \x01(\x05R\n" +
	"totalParts\"W\n" +
	"\x19GetPartUploadURLsResponse\x12\x1b\n" +
	"\tpart_urls\x18\x01 \x03(\tR\bpartUrls\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"g\n" +
	"\x1eCompleteMultipartUploadRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12*\n" +
	"\x05parts\x18\x02 \x03(\v2\x14.video.CompletedPartR\x05parts\"D\n" +
	"\rCompletedPart\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"X\n" +
	"\x1fCompleteMultipartUploadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\",\n" +
	"\x0fGetVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"6\n" +
	"\x10GetVideoResponse\x12\"\n" +
	"\x05video\x18\x01 \x01(\v2\f.video.VideoR\x05video\"\\\n" +
	"\x13SearchVideosRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"]\n" +
	"\x14SearchVideosResponse\x12$\n" +
	"\x06videos\x18\x01 \x03(\v2\f.video.VideoR\x06videos\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xd8\x01\n" +
	"\x05Video\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12&\n" +
	"\x0ffile_size_bytes\x18\x03 \x01(\x03R\rfileSizeBytes\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05R\x0fdurationSeconds\x12#\n" +
	"\rupload_status\x18\x05 \x01(\tR\fuploadStatus\x12\x1f\n" +
	"\vuploaded_at\x18\x06 \x01(\x03R\n" +
	"uploadedAt\"]\n" +
	"\x16CreateShareLinkRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12(\n" +
	"\x10expires_in_hours\x18\x02 \x01(\x05R\x0eexpiresInHours\"U\n" +
	"\x17CreateShareLinkResponse\x12\x1b\n" +
	"\tshare_url\x18\x01 \x01(\tR\bshareUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"8\n" +
	"\x15GetPublicVideoRequest\x12\x1f\n" +
	"\vshare_token\x18\x01 \x01(\tR\n" +
	"shareToken\"\x94\x01\n" +
	"\x16GetPublicVideoResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"3\n" +
	"\x16RevokeShareLinkRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"3\n" +
	"\x17RevokeShareLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb9\x05\n" +
	"\fVideoService\x12h\n" +
	"\x17InitiateMultipartUpload\x12%.video.InitiateMultipartUploadRequest\x1a&.video.InitiateMultipartUploadResponse\x12V\n" +
	"\x11GetPartUploadURLs\x12\x1f.video.GetPartUploadURLsRequest\x1a .video.GetPartUploadURLsResponse\x12h\n" +
	"\x17CompleteMultipartUpload\x12%.video.CompleteMultipartUploadRequest\x1a&.video.CompleteMultipartUploadResponse\x12;\n" +
	"\bGetVideo\x12\x16.video.GetVideoRequest\x1a\x17.video.GetVideoResponse\x12G\n" +
	"\fSearchVideos\x12\x1a.video.SearchVideosRequest\x1a\x1b.video.SearchVideosResponse\x12V\n" +
	"\x15CreatePublicShareLink\x12\x1d.video.CreateShareLinkRequest\x1a\x1e.video.CreateShareLinkResponse\x12M\n" +
	"\x0eGetPublicVideo\x12\x1c.video.GetPublicVideoRequest\x1a\x1d.video.GetPublicVideoResponse\x12P\n" +
	"\x0fRevokeShareLink\x12\x1d.video.RevokeShareLinkRequest\x1a\x1e.video.RevokeShareLinkResponseB0Z.github.com/lumiforge/sellerproof-backend/protob\x06proto3"

var (
	file_proto_video_proto_rawDescOnce sync.Once
	file_proto_video_proto_rawDescData []byte
)

func file_proto_video_proto_rawDescGZIP() []byte {
	file_proto_video_proto_rawDescOnce.Do(func() {
		file_proto_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)))
	})
	return file_proto_video_proto_rawDescData
}

var file_proto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_video_proto_goTypes = []any{
	(*InitiateMultipartUploadRequest)(nil),  // 0: video.InitiateMultipartUploadRequest
	(*InitiateMultipartUploadResponse)(nil), // 1: video.InitiateMultipartUploadResponse
	(*GetPartUploadURLsRequest)(nil),        // 2: video.GetPartUploadURLsRequest
	(*GetPartUploadURLsResponse)(nil),       // 3: video.GetPartUploadURLsResponse
	(*CompleteMultipartUploadRequest)(nil),  // 4: video.CompleteMultipartUploadRequest
	(*CompletedPart)(nil),                   // 5: video.CompletedPart
	(*CompleteMultipartUploadResponse)(nil), // 6: video.CompleteMultipartUploadResponse
	(*GetVideoRequest)(nil),                 // 7: video.GetVideoRequest
	(*GetVideoResponse)(nil),                // 8: video.GetVideoResponse
	(*SearchVideosRequest)(nil),             // 9: video.SearchVideosRequest
	(*SearchVideosResponse)(nil),            // 10: video.SearchVideosResponse
	(*Video)(nil),                           // 11: video.Video
	(*CreateShareLinkRequest)(nil),          // 12: video.CreateShareLinkRequest
	(*CreateShareLinkResponse)(nil),         // 13: video.CreateShareLinkResponse
	(*GetPublicVideoRequest)(nil),           // 14: video.GetPublicVideoRequest
	(*GetPublicVideoResponse)(nil),          // 15: video.GetPublicVideoResponse
	(*RevokeShareLinkRequest)(nil),          // 16: video.RevokeShareLinkRequest
	(*RevokeShareLinkResponse)(nil),         // 17: video.RevokeShareLinkResponse
}
var file_proto_video_proto_depIdxs = []int32{
	5,  // 0: video.CompleteMultipartUploadRequest.parts:type_name -> video.CompletedPart
	11, // 1: video.GetVideoResponse.video:type_name -> video.Video
	11, // 2: video.SearchVideosResponse.videos:type_name -> video.Video
	0,  // 3: video.VideoService.InitiateMultipartUpload:input_type -> video.InitiateMultipartUploadRequest
	2,  // 4: video.VideoService.GetPartUploadURLs:input_type -> video.GetPartUploadURLsRequest
	4,  // 5: video.VideoService.CompleteMultipartUpload:input_type -> video.CompleteMultipartUploadRequest
	7,  // 6: video.VideoService.GetVideo:input_type -> video.GetVideoRequest
	9,  // 7: video.VideoService.SearchVideos:input_type -> video.SearchVideosRequest
	12, // 8: video.VideoService.CreatePublicShareLink:input_type -> video.CreateShareLinkRequest
	14, // 9: video.VideoService.GetPublicVideo:input_type -> video.GetPublicVideoRequest
	16, // 10: video.VideoService.RevokeShareLink:input_type -> video.RevokeShareLinkRequest
	1,  // 11: video.VideoService.InitiateMultipartUpload:output_type -> video.InitiateMultipartUploadResponse
	3,  // 12: video.VideoService.GetPartUploadURLs:output_type -> video.GetPartUploadURLsResponse
	6,  // 13: video.VideoService.CompleteMultipartUpload:output_type -> video.CompleteMultipartUploadResponse
	8,  // 14: video.VideoService.GetVideo:output_type -> video.GetVideoResponse
	10, // 15: video.VideoService.SearchVideos:output_type -> video.SearchVideosResponse
	13, // 16: video.VideoService.CreatePublicShareLink:output_type -> video.CreateShareLinkResponse
	15, // 17: video.VideoService.GetPublicVideo:output_type -> video.GetPublicVideoResponse
	17, // 18: video.VideoService.RevokeShareLink:output_type -> video.RevokeShareLinkResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_video_proto_init() }
func file_proto_video_proto_init() {
	if File_proto_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_proto_goTypes,
		DependencyIndexes: file_proto_video_proto_depIdxs,
		MessageInfos:      file_proto_video_proto_msgTypes,
	}.Build()
	File_proto_video_proto = out.File
	file_proto_video_proto_goTypes = nil
	file_proto_video_proto_depIdxs = nil
}
