openapi: 3.0.0
info:
  title: SellerProof API
  version: 1.0.0
  description: REST API для SellerProof Backend с wildcard routing

servers:
  - url: https://d5dok9vujep8na8ceadj.4b4k4pg5.apigw.yandexcloud.net
    description: Production API Gateway

paths:
  /{proxy+}:
    x-yc-apigateway-any-method:
      operationId: proxyToFunction
      summary: Проксирование всех запросов в Cloud Function
      description: |
        Все HTTP запросы проксируются в Cloud Function,
        где происходит роутинг на основе path и method.
        Это позволяет добавлять новые endpoints без изменения API Gateway.
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ee6jtu2bncp61ovrmt
        service_account_id: aje77nc6pfha5nlegvba
        payload_format_version: '1.0'
      parameters:
        - name: proxy
          in: path
          required: false
          schema:
            type: string
            default: ''
          style: simple
          explode: false
          description: Путь запроса (будет передан в Cloud Function)
      responses:
        '200':
          description: Успешный ответ
        '400':
          description: Неверный запрос
        '401':
          description: Не авторизован
        '403':
          description: Доступ запрещён
        '404':
          description: Не найдено
        '500':
          description: Внутренняя ошибка сервера
