package errors

import "errors"

var (
	// Generic errors
	ErrConnectionLost     = errors.New("connection lost")
	ErrNotFound           = errors.New("not found")
	ErrDBConnectionFailed = errors.New("db connection failed")
	ErrUnauthorized       = errors.New("unauthorized")
	ErrForbidden          = errors.New("forbidden")
	ErrBadRequest         = errors.New("bad request")
	ErrInternalServer     = errors.New("internal server error")
	ErrInvalidCredentials = errors.New("invalid credentials")
	ErrInvalidRequest     = errors.New("invalid request")

	// HTTP Handler errors
	ErrUserNotAuthenticated                      = errors.New("user not authenticated")
	ErrInvalidRequestFormat                      = errors.New("invalid request format")
	ErrRefreshTokenCannotContainTrailingSpaces   = errors.New("refresh token cannot contain trailing spaces")
	ErrRefreshTokenRequired                      = errors.New("refresh token is required")
	ErrFileSizeMustBeNumber                      = errors.New("file_size_bytes must be a number, not a string")
	ErrDurationMustBeNumber                      = errors.New("duration_seconds must be a number, not a string")
	ErrFileSizeMustBePositive                    = errors.New("file_size_bytes must be greater than 0")
	ErrDurationMustBePositive                    = errors.New("duration_seconds must be greater than 0")
	ErrValidationError                           = errors.New("validation error")
	ErrMinimum1PartRequired                      = errors.New("minimum 1 part required")
	ErrMaximum100PartsAllowed                    = errors.New("maximum 100 parts allowed")
	ErrVideoIDRequired                           = errors.New("video_id is required")
	ErrInvalidVideoID                            = errors.New("invalid video_id")
	ErrInvalidVideoIDMustBeUUID                  = errors.New("invalid video_id: must be a valid UUID")
	ErrVideoNotFoundInvalidVideoID               = errors.New("invalid video_id: video not found")
	ErrPartsRequired                             = errors.New("parts is required")
	ErrPartNumberMustBePositive                  = errors.New("part_number must be greater than 0")
	ErrETagRequired                              = errors.New("etag is required")
	ErrInvalidQuery                              = errors.New("invalid query")
	ErrMissingOrInvalidTokenParameter            = errors.New("missing or invalid token parameter")
	ErrInvalidTokenFormat                        = errors.New("invalid token format")
	ErrInvalidToken2                             = errors.New("invalid token")
	ErrVideoNotFoundOrTokenInvalid2              = errors.New("video not found or token is invalid")
	ErrPublicAccessRevokedMessage                = errors.New("public access to this video has been revoked")
	ErrFailedToRetrieveVideo                     = errors.New("failed to retrieve video")
	ErrOrgIDRequired                             = errors.New("org_id is required")
	ErrInvalidOrgID                              = errors.New("invalid org_id")
	ErrInvalidOrgIDMustBeUUID                    = errors.New("invalid org_id: must be a valid UUID")
	ErrAccessDeniedNotMember                     = errors.New("access denied: you are not a member of this organization")
	ErrOnlyAdminsCanCreateOrganizations          = errors.New("only admins can create organizations")
	ErrOnlyAdminsAndManagersCanListInvitations   = errors.New("only admins and managers can list invitations")
	ErrInvitationIDRequired                      = errors.New("invitation_id is required")
	ErrInvalidInvitationIDMustBeUUID             = errors.New("invalid invitation_id: must be a valid UUID")
	ErrOnlyAdminsAndManagersCanCancelInvitations = errors.New("only admins and managers can cancel invitations")
	ErrOnlyAdminsCanListMembers                  = errors.New("only admins can list members")
	ErrOnlyAdminsCanUpdateMemberRoles            = errors.New("only admins can update member roles")
	ErrUserIDRequired                            = errors.New("user_id is required")
	ErrOnlyAdminsCanRemoveMembers2               = errors.New("only admins can remove members")
	ErrOnlyAdminsAndManagersCanPublishVideos     = errors.New("only admins and managers can publish videos")
	ErrMissingRequiredFieldVideoID               = errors.New("missing required field: video_id")
	ErrOnlyAdminsAndManagersCanRevokeVideoAccess = errors.New("only admins and managers can revoke video access")
	ErrVideoNotFoundMessage                      = errors.New("video not found")
	ErrAccessDeniedMessage                       = errors.New("access denied")
	ErrFailedToGetVideoMessage                   = errors.New("failed to get video")
	ErrVideoIsNotPublished                       = errors.New("video is not published")
	ErrUnauthorizedMessage                       = errors.New("unauthorized")
	ErrInsufficientPermissionsToAccessAuditLogs  = errors.New("insufficient permissions to access audit logs")
	ErrOffsetCannotExceed10000                   = errors.New("offset cannot exceed 10000. please use date filters to narrow down results")
	ErrFailedToRetrieveAuditLogs                 = errors.New("failed to retrieve audit logs")
	ErrFailedToProcessRequest                    = errors.New("failed to process request")
	ErrFailedToDeleteOrganization                = errors.New("failed to delete organization")
	ErrOrganizationNotFoundOrAccessDenied        = errors.New("organization not found or access denied")
	ErrFailedToUpdateOrganizationName            = errors.New("failed to update organization name")
	ErrFailedToGetSubscriptionDetails            = errors.New("failed to get subscription details")
	ErrFailedToRetrievePlans                     = errors.New("failed to retrieve plans")

	// Auth errors
	ErrEmailRequired                        = errors.New("email is required")
	ErrPasswordRequired                     = errors.New("password is required")
	ErrFullNameRequired                     = errors.New("full_name is required")
	ErrOrgNameOrInviteCodeRequired          = errors.New("organization_name or invite_code is required")
	ErrPasswordTooShort                     = errors.New("password must be at least 8 characters long")
	ErrPasswordTooLong                      = errors.New("password must be less than 73 characters long")
	ErrFullNameTooShort                     = errors.New("full_name must be at least 2 characters long")
	ErrFullNameTooLong                      = errors.New("full_name must be less than 101 characters long")
	ErrOrgNameTooLong                       = errors.New("organization_name must be less than 201 characters long")
	ErrInvalidInviteCode                    = errors.New("invalid invite code")
	ErrInvitationNotPending                 = errors.New("invitation is not pending")
	ErrInvitationExpired                    = errors.New("invitation has expired")
	ErrRegistrationEmailMismatch            = errors.New("registration email does not match invitation email")
	ErrFailedToGenerateVerificationCode     = errors.New("failed to generate verification code")
	ErrFailedToUpdateUser                   = errors.New("failed to update user")
	ErrEmailAlreadyExists                   = errors.New("email already exists")
	ErrFailedToHashPassword                 = errors.New("failed to hash password")
	ErrFailedToFetchFreePlan                = errors.New("failed to fetch free plan details")
	ErrRegistrationFailed                   = errors.New("registration failed")
	ErrUserNotFound                         = errors.New("user not found")
	ErrTooManyFailedAttempts                = errors.New("too many failed attempts. please request a new verification code")
	ErrVerificationCodeExpired              = errors.New("verification code expired")
	ErrInvalidVerificationCode              = errors.New("invalid verification code")
	ErrEmailTooLong                         = errors.New("email must be less than 255 characters long")
	ErrEmailNotVerified                     = errors.New("email not verified")
	ErrUserAccountDeactivated               = errors.New("user account is deactivated")
	ErrFailedToGetUserMembership            = errors.New("failed to get user membership")
	ErrMembershipNotFound                   = errors.New("membership not found")
	ErrFailedToGetOrganizations             = errors.New("failed to get organizations")
	ErrNoValidOrganizations                 = errors.New("no valid organizations found for user")
	ErrFailedToGenerateTokens               = errors.New("failed to generate tokens")
	ErrFailedToCreateSession                = errors.New("failed to create session")
	ErrInvalidRefreshToken                  = errors.New("invalid refresh token")
	ErrRefreshTokenNotFoundOrRevoked        = errors.New("refresh token not found or revoked")
	ErrMembershipNotFoundOrRevoked          = errors.New("membership not found or revoked")
	ErrMembershipNotActive                  = errors.New("membership is not active")
	ErrFailedToGenerateNewTokens            = errors.New("failed to generate new tokens")
	ErrFailedToRevokeRefreshToken           = errors.New("failed to revoke refresh token")
	ErrRefreshTokenExpired                  = errors.New("refresh token expired")
	ErrRefreshTokenDoesNotBelongToUser      = errors.New("refresh token does not belong to user")
	ErrFailedToRevokeOldToken               = errors.New("failed to revoke old token")
	ErrRoleRequired                         = errors.New("role is required")
	ErrInvalidRole                          = errors.New("invalid role")
	ErrInviterNotMember                     = errors.New("inviter is not a member of this organization")
	ErrOnlyAdminsAndManagersCanInvite       = errors.New("only admins and managers can invite users")
	ErrManagersCannotInviteAdmins           = errors.New("managers cannot invite admins")
	ErrFailedToCheckExistingInvitations     = errors.New("failed to check existing invitations")
	ErrUserAlreadyInvited                   = errors.New("user already invited to this organization")
	ErrUserIsAlreadyMember                  = errors.New("user is already a member of this organization")
	ErrFailedToCreateInvitation             = errors.New("failed to create invitation")
	ErrInviteCodeRequired                   = errors.New("invite_code is required")
	ErrFailedToCreateMembership             = errors.New("failed to create membership")
	ErrFailedToGetInvitations               = errors.New("failed to get invitations")
	ErrInvitationNotFound                   = errors.New("invitation not found")
	ErrOnlyPendingInvitationsCanBeCancelled = errors.New("only pending invitations can be cancelled")
	ErrFailedToCancelInvitation             = errors.New("failed to cancel invitation")
	ErrOnlyAdminsCanChangeRoles             = errors.New("only admins can change roles")
	ErrTargetUserNotMember                  = errors.New("target user is not a member of this organization")
	ErrFailedToGetOrganizationInfo          = errors.New("failed to get organization info")
	ErrCannotChangeRoleOfOrgOwner           = errors.New("cannot change role of organization owner")
	ErrFailedToUpdateMemberRole             = errors.New("failed to update member role")
	ErrOnlyAdminsCanRemoveMembers           = errors.New("only admins can remove members")
	ErrCannotRemoveOrgOwner                 = errors.New("cannot remove organization owner")
	ErrFailedToRemoveMember                 = errors.New("failed to remove member")
	ErrInvalidStatus                        = errors.New("invalid status")
	ErrInsufficientPermissions              = errors.New("insufficient permissions")
	ErrManagersCannotManageAdmins           = errors.New("managers cannot manage admins or other managers")
	ErrCannotChangeStatusOfOrgOwner         = errors.New("cannot change status of organization owner")
	ErrFailedToGetMembers                   = errors.New("failed to get members")
	ErrRequestIsRequired                    = errors.New("request is required")
	ErrFailedToGetUserMemberships           = errors.New("failed to get user memberships")
	ErrOnlyAdminsCanCreateOrgs              = errors.New("only admins can create organizations")
	ErrFailedToGetUserOrgs                  = errors.New("failed to get user organizations")
	ErrFailedToMarshalOrgSettings           = errors.New("failed to marshal organization settings")
	ErrFailedToCreateOrg                    = errors.New("failed to create organization")
	ErrMembershipNotActiveOrRevoked         = errors.New("membership is not active or revoked")
	ErrFailedToGenerateResetCode            = errors.New("failed to generate reset code")
	ErrFailedToSaveResetCode                = errors.New("failed to save reset code")
	ErrPasswordWrongLength                  = errors.New("password must be between 8 and 72 characters")
	ErrInvalidResetCode                     = errors.New("invalid reset code")
	ErrResetCodeExpired                     = errors.New("reset code expired")
	ErrFailedToUpdatePassword               = errors.New("failed to update password")
	ErrOrgCanHaveOnlyOneAdmin               = errors.New("organization can have only one admin")
	ErrOnlyOwnerCanDeleteOrg                = errors.New("only organization owner can delete it")

	// Success messages
	MsgRegistrationSuccessful          = errors.New("registration successful. please check your email for verification")
	MsgInvitationCancelledSuccessfully = errors.New("invitation cancelled successfully")
	MsgMemberRoleUpdatedSuccessfully   = errors.New("member role updated successfully")
	MsgMemberStatusUpdatedSuccessfully = errors.New("member status updated successfully")
	MsgMemberRemovedSuccessfully       = errors.New("member removed successfully")
	MsgVideoAccessRevokedSuccessfully  = errors.New("video access revoked successfully")
	MsgOrganizationDeletedSuccessfully = errors.New("organization deleted successfully")
	MsgStatusPrivate                   = errors.New("private")
	MsgEmailAlreadyVerified            = errors.New("email already verified")

	// Bootstrap errors
	ErrFailedToConnectYDB        = errors.New("failed to connect to YDB")
	ErrJWTSecretKeyNotConfigured = errors.New("JWT secret key is not configured")
	ErrFailedToInitStorageClient = errors.New("failed to initialize storage client")

	// JWT errors
	ErrFailedToGenerateAccessToken  = errors.New("failed to generate access token")
	ErrFailedToGenerateRefreshToken = errors.New("failed to generate refresh token")
	ErrUnexpectedSigningMethod      = errors.New("unexpected signing method")
	ErrFailedToParseToken           = errors.New("failed to parse token")
	ErrInvalidToken                 = errors.New("invalid token")
	ErrAuthHeaderEmpty              = errors.New("authorization header is empty")
	ErrAuthHeaderWrongFormat        = errors.New("authorization header format must be Bearer {token}")

	// Email errors
	ErrPostboxCredentialsNotConfigured = errors.New("Postbox credentials not configured")

	// RBAC errors
	ErrUserRoleNotFoundInContext = errors.New("user role not found in context")

	// Storage errors
	ErrObjectKeyRequired           = errors.New("object key is required")
	ErrAWSCredsOrBucketNamesNotSet = errors.New("AWS credentials and bucket names must be set")
	ErrFailedToLoadAWSConfig       = errors.New("failed to load aws config")
	ErrFailedToParseEndpointURL    = errors.New("failed to parse endpoint url")

	// Video errors
	ErrAccessDenied                    = errors.New("access denied")
	ErrVideoNotFound                   = errors.New("video not found")
	ErrFailedToReadVideo               = errors.New("failed to read video")
	ErrFailedToDeleteVideoFromStorage  = errors.New("failed to delete video from storage")
	ErrFailedToUpdateVideoRecord       = errors.New("failed to update video record")
	ErrFailedToGetSubscription         = errors.New("failed to get subscription")
	ErrFailedToGetStorageUsage         = errors.New("failed to get storage usage")
	ErrVideoSizeLimitExceeded          = errors.New("video size limit exceeded")
	ErrInvalidFileType                 = errors.New("invalid file type or extension. Only video files are allowed")
	ErrFailedToInitiateS3Upload        = errors.New("failed to initiate s3 upload")
	ErrFailedToCreateVideoRecord       = errors.New("failed to create video record")
	ErrUploaderOnlyCanGenUploadURLs    = errors.New("access denied: only uploader can generate upload urls")
	ErrVideoIsDeleted                  = errors.New("video is deleted")
	ErrVideoUploadAlreadyCompleted     = errors.New("video upload is already completed")
	ErrFailedToGenerateURLForPart      = errors.New("failed to generate url for part")
	ErrFailedToUpdateVideoStatus       = errors.New("failed to update video status")
	ErrFailedToCompleteS3Upload        = errors.New("failed to complete s3 upload")
	ErrFailedToVerifyFileIntegrity     = errors.New("failed to verify file integrity")
	ErrInvalidFileContent              = errors.New("invalid file content")
	ErrFailedToVerifyUploadIntegrity   = errors.New("failed to verify upload integrity")
	ErrOnlyAdminsAndManagersCanPublish = errors.New("access denied: only admins and managers can publish")
	ErrFailedToPublishVideo            = errors.New("failed to publish video")
	ErrVideoUploadNotCompleted         = errors.New("video upload not completed")
	ErrFailedToCheckActiveShare        = errors.New("failed to check active share")
	ErrFailedToCopyVideoToPublic       = errors.New("failed to copy video to public bucket")
	ErrFailedToGeneratePublicToken     = errors.New("failed to generate public token")
	ErrFailedToPublishVideoRecord      = errors.New("failed to publish video record")
	ErrVideoNotFoundOrTokenInvalid     = errors.New("video not found or token is invalid")
	ErrPublicAccessRevoked             = errors.New("public access to this video has been revoked")
	ErrFailedToGenerateStreamURL       = errors.New("failed to generate stream URL")
	ErrFailedToGetVideo                = errors.New("failed to get video")
	ErrFailedToGeneratePresignedURL    = errors.New("failed to generate presigned URL")
	ErrOnlyAdminsAndManagersCanRevoke  = errors.New("access denied: only admins and managers can revoke")
	ErrVideoNotPublished               = errors.New("video is not published")
	ErrFailedToCopyVideoToPrivate      = errors.New("failed to copy video to private bucket")
	ErrFailedToGetPublicShare          = errors.New("failed to get public share")
	ErrSubscriptionExpired             = errors.New("subscription expired")

	// YDB errors
	ErrYDBCredentialsNotProvided = errors.New("YDB credentials not provided. Please set SP_YDB_ENDPOINT and SP_YDB_DATABASE_PATH environment variables")
	ErrFailedToCreateTables      = errors.New("failed to create tables")
	ErrScanFailed                = errors.New("scan failed")
)
