// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/lumiforge/sellerproof-backend/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	ydb "github.com/lumiforge/sellerproof-backend/internal/ydb"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// CleanupExpiredTokens provides a mock function with given fields: ctx
func (_m *Database) CleanupExpiredTokens(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *Database) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEmailLog provides a mock function with given fields: ctx, log
func (_m *Database) CreateEmailLog(ctx context.Context, log *ydb.EmailLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmailLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.EmailLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateInvitation provides a mock function with given fields: ctx, invitation
func (_m *Database) CreateInvitation(ctx context.Context, invitation *ydb.Invitation) error {
	ret := _m.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Invitation) error); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMembership provides a mock function with given fields: ctx, membership
func (_m *Database) CreateMembership(ctx context.Context, membership *ydb.Membership) error {
	ret := _m.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for CreateMembership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Membership) error); ok {
		r0 = rf(ctx, membership)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrganization provides a mock function with given fields: ctx, org
func (_m *Database) CreateOrganization(ctx context.Context, org *ydb.Organization) error {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Organization) error); ok {
		r0 = rf(ctx, org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePublicVideoShare provides a mock function with given fields: ctx, share
func (_m *Database) CreatePublicVideoShare(ctx context.Context, share *ydb.PublicVideoShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for CreatePublicVideoShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.PublicVideoShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRefreshToken provides a mock function with given fields: ctx, token
func (_m *Database) CreateRefreshToken(ctx context.Context, token *ydb.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSubscription provides a mock function with given fields: ctx, subscription
func (_m *Database) CreateSubscription(ctx context.Context, subscription *ydb.Subscription) error {
	ret := _m.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Subscription) error); ok {
		r0 = rf(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSubscriptionHistory provides a mock function with given fields: ctx, history
func (_m *Database) CreateSubscriptionHistory(ctx context.Context, history *ydb.SubscriptionHistory) error {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscriptionHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.SubscriptionHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *Database) CreateUser(ctx context.Context, user *ydb.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateVideo provides a mock function with given fields: ctx, video
func (_m *Database) CreateVideo(ctx context.Context, video *ydb.Video) error {
	ret := _m.Called(ctx, video)

	if len(ret) == 0 {
		panic("no return value specified for CreateVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Video) error); ok {
		r0 = rf(ctx, video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInvitation provides a mock function with given fields: ctx, invitationID
func (_m *Database) DeleteInvitation(ctx context.Context, invitationID string) error {
	ret := _m.Called(ctx, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, invitationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMembership provides a mock function with given fields: ctx, membershipID
func (_m *Database) DeleteMembership(ctx context.Context, membershipID string) error {
	ret := _m.Called(ctx, membershipID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMembership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, membershipID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *Database) DeleteUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOrganizationTx provides a mock function with given fields: ctx, orgID
func (_m *Database) DeleteOrganizationTx(ctx context.Context, orgID string) error {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActivePublicVideoShare provides a mock function with given fields: ctx, videoID
func (_m *Database) GetActivePublicVideoShare(ctx context.Context, videoID string) (*ydb.PublicVideoShare, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivePublicVideoShare")
	}

	var r0 *ydb.PublicVideoShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.PublicVideoShare, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.PublicVideoShare); ok {
		r0 = rf(ctx, videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.PublicVideoShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPlans provides a mock function with given fields: ctx
func (_m *Database) GetAllPlans(ctx context.Context) ([]*ydb.Plan, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlans")
	}

	var r0 []*ydb.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*ydb.Plan, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*ydb.Plan); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuditLogs provides a mock function with given fields: ctx, filters, limit, offset
func (_m *Database) GetAuditLogs(ctx context.Context, filters map[string]interface{}, limit int, offset int) ([]*models.AuditLog, int64, error) {
	ret := _m.Called(ctx, filters, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLogs")
	}

	var r0 []*models.AuditLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, int, int) ([]*models.AuditLog, int64, error)); ok {
		return rf(ctx, filters, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, int, int) []*models.AuditLog); ok {
		r0 = rf(ctx, filters, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}, int, int) int64); ok {
		r1 = rf(ctx, filters, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, map[string]interface{}, int, int) error); ok {
		r2 = rf(ctx, filters, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetEmailLogsByUser provides a mock function with given fields: ctx, userID
func (_m *Database) GetEmailLogsByUser(ctx context.Context, userID string) ([]*ydb.EmailLog, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEmailLogsByUser")
	}

	var r0 []*ydb.EmailLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.EmailLog, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.EmailLog); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.EmailLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvitationByCode provides a mock function with given fields: ctx, code
func (_m *Database) GetInvitationByCode(ctx context.Context, code string) (*ydb.Invitation, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationByCode")
	}

	var r0 *ydb.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Invitation, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Invitation); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvitationByEmail provides a mock function with given fields: ctx, orgID, email
func (_m *Database) GetInvitationByEmail(ctx context.Context, orgID string, email string) (*ydb.Invitation, error) {
	ret := _m.Called(ctx, orgID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationByEmail")
	}

	var r0 *ydb.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ydb.Invitation, error)); ok {
		return rf(ctx, orgID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ydb.Invitation); ok {
		r0 = rf(ctx, orgID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvitationByID provides a mock function with given fields: ctx, invitationID
func (_m *Database) GetInvitationByID(ctx context.Context, invitationID string) (*ydb.Invitation, error) {
	ret := _m.Called(ctx, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationByID")
	}

	var r0 *ydb.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Invitation, error)); ok {
		return rf(ctx, invitationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Invitation); ok {
		r0 = rf(ctx, invitationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, invitationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvitationsByOrg provides a mock function with given fields: ctx, orgID
func (_m *Database) GetInvitationsByOrg(ctx context.Context, orgID string) ([]*ydb.Invitation, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitationsByOrg")
	}

	var r0 []*ydb.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.Invitation, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.Invitation); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembership provides a mock function with given fields: ctx, userID, orgID
func (_m *Database) GetMembership(ctx context.Context, userID string, orgID string) (*ydb.Membership, error) {
	ret := _m.Called(ctx, userID, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembership")
	}

	var r0 *ydb.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ydb.Membership, error)); ok {
		return rf(ctx, userID, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ydb.Membership); ok {
		r0 = rf(ctx, userID, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembershipsByOrg provides a mock function with given fields: ctx, orgID
func (_m *Database) GetMembershipsByOrg(ctx context.Context, orgID string) ([]*ydb.Membership, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembershipsByOrg")
	}

	var r0 []*ydb.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.Membership, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.Membership); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembershipsByUser provides a mock function with given fields: ctx, userID
func (_m *Database) GetMembershipsByUser(ctx context.Context, userID string) ([]*ydb.Membership, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembershipsByUser")
	}

	var r0 []*ydb.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.Membership, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.Membership); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByID provides a mock function with given fields: ctx, orgID
func (_m *Database) GetOrganizationByID(ctx context.Context, orgID string) (*ydb.Organization, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 *ydb.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Organization, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Organization); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationsByIDs provides a mock function with given fields: ctx, orgIDs
func (_m *Database) GetOrganizationsByIDs(ctx context.Context, orgIDs []string) ([]*ydb.Organization, error) {
	ret := _m.Called(ctx, orgIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationsByIDs")
	}

	var r0 []*ydb.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*ydb.Organization, error)); ok {
		return rf(ctx, orgIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*ydb.Organization); ok {
		r0 = rf(ctx, orgIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, orgIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationsByOwner provides a mock function with given fields: ctx, ownerID
func (_m *Database) GetOrganizationsByOwner(ctx context.Context, ownerID string) ([]*ydb.Organization, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationsByOwner")
	}

	var r0 []*ydb.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.Organization, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.Organization); ok {
		r0 = rf(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlanByID provides a mock function with given fields: ctx, planID
func (_m *Database) GetPlanByID(ctx context.Context, planID string) (*ydb.Plan, error) {
	ret := _m.Called(ctx, planID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanByID")
	}

	var r0 *ydb.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Plan, error)); ok {
		return rf(ctx, planID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Plan); ok {
		r0 = rf(ctx, planID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicVideoShareByToken provides a mock function with given fields: ctx, token
func (_m *Database) GetPublicVideoShareByToken(ctx context.Context, token string) (*ydb.PublicVideoShare, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicVideoShareByToken")
	}

	var r0 *ydb.PublicVideoShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.PublicVideoShare, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.PublicVideoShare); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.PublicVideoShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *Database) GetRefreshToken(ctx context.Context, tokenHash string) (*ydb.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *ydb.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefreshTokensByUser provides a mock function with given fields: ctx, userID
func (_m *Database) GetRefreshTokensByUser(ctx context.Context, userID string) ([]*ydb.RefreshToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokensByUser")
	}

	var r0 []*ydb.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.RefreshToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.RefreshToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStorageUsage provides a mock function with given fields: ctx, ownerID
func (_m *Database) GetStorageUsage(ctx context.Context, ownerID string, subscriptionStartDate time.Time) (int64, error) {
	ret := _m.Called(ctx, ownerID, subscriptionStartDate)

	if len(ret) == 0 {
		panic("no return value specified for GetStorageUsage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (int64, error)); ok {
		return rf(ctx, ownerID, subscriptionStartDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) int64); ok {
		r0 = rf(ctx, ownerID, subscriptionStartDate)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, ownerID, subscriptionStartDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionByID provides a mock function with given fields: ctx, subscriptionID
func (_m *Database) GetSubscriptionByID(ctx context.Context, subscriptionID string) (*ydb.Subscription, error) {
	ret := _m.Called(ctx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByID")
	}

	var r0 *ydb.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Subscription, error)); ok {
		return rf(ctx, subscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Subscription); ok {
		r0 = rf(ctx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionByUser provides a mock function with given fields: ctx, userID
func (_m *Database) GetSubscriptionByUser(ctx context.Context, userID string) (*ydb.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByUser")
	}

	var r0 *ydb.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionHistory provides a mock function with given fields: ctx, subscriptionID
func (_m *Database) GetSubscriptionHistory(ctx context.Context, subscriptionID string) ([]*ydb.SubscriptionHistory, error) {
	ret := _m.Called(ctx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionHistory")
	}

	var r0 []*ydb.SubscriptionHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ydb.SubscriptionHistory, error)); ok {
		return rf(ctx, subscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ydb.SubscriptionHistory); ok {
		r0 = rf(ctx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.SubscriptionHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Database) GetUserByEmail(ctx context.Context, email string) (*ydb.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *ydb.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *Database) GetUserByID(ctx context.Context, userID string) (*ydb.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *ydb.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideo provides a mock function with given fields: ctx, videoID
func (_m *Database) GetVideo(ctx context.Context, videoID string) (*ydb.Video, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetVideo")
	}

	var r0 *ydb.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Video, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Video); ok {
		r0 = rf(ctx, videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideoByShareToken provides a mock function with given fields: ctx, token
func (_m *Database) GetVideoByShareToken(ctx context.Context, token string) (*ydb.Video, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetVideoByShareToken")
	}

	var r0 *ydb.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ydb.Video, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ydb.Video); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ydb.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementAccessCount provides a mock function with given fields: ctx, token
func (_m *Database) IncrementAccessCount(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAccessCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Initialize provides a mock function with given fields: ctx
func (_m *Database) Initialize(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertAuditLog provides a mock function with given fields: ctx, auditLog
func (_m *Database) InsertAuditLog(ctx context.Context, auditLog *models.AuditLog) error {
	ret := _m.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for InsertAuditLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AuditLog) error); ok {
		r0 = rf(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishVideoTx provides a mock function with given fields: ctx, share, videoID, publicURL, status
func (_m *Database) PublishVideoTx(ctx context.Context, share *ydb.PublicVideoShare, videoID string, publicURL string, status string) error {
	ret := _m.Called(ctx, share, videoID, publicURL, status)

	if len(ret) == 0 {
		panic("no return value specified for PublishVideoTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.PublicVideoShare, string, string, string) error); ok {
		r0 = rf(ctx, share, videoID, publicURL, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterUserTx provides a mock function with given fields: ctx, user, org, membership, subscription, invitationID
func (_m *Database) RegisterUserTx(ctx context.Context, user *ydb.User, org *ydb.Organization, membership *ydb.Membership, subscription *ydb.Subscription, invitationID string) error {
	ret := _m.Called(ctx, user, org, membership, subscription, invitationID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUserTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.User, *ydb.Organization, *ydb.Membership, *ydb.Subscription, string) error); ok {
		r0 = rf(ctx, user, org, membership, subscription, invitationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllUserRefreshTokens provides a mock function with given fields: ctx, userID
func (_m *Database) RevokeAllUserRefreshTokens(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokePublicVideoShare provides a mock function with given fields: ctx, videoID, userID
func (_m *Database) RevokePublicVideoShare(ctx context.Context, videoID string, userID string) error {
	ret := _m.Called(ctx, videoID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokePublicVideoShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, videoID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *Database) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchVideos provides a mock function with given fields: ctx, orgID, userID, query, limit, offset
func (_m *Database) SearchVideos(ctx context.Context, orgID string, userID string, query string, limit int, offset int) ([]*ydb.Video, int64, error) {
	ret := _m.Called(ctx, orgID, userID, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchVideos")
	}

	var r0 []*ydb.Video
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]*ydb.Video, int64, error)); ok {
		return rf(ctx, orgID, userID, query, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []*ydb.Video); ok {
		r0 = rf(ctx, orgID, userID, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ydb.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int64); ok {
		r1 = rf(ctx, orgID, userID, query, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = rf(ctx, orgID, userID, query, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateEmailLog provides a mock function with given fields: ctx, log
func (_m *Database) UpdateEmailLog(ctx context.Context, log *ydb.EmailLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmailLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.EmailLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateInvitationStatus provides a mock function with given fields: ctx, invitationID, status
func (_m *Database) UpdateInvitationStatus(ctx context.Context, invitationID string, status string) error {
	ret := _m.Called(ctx, invitationID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInvitationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, invitationID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateInvitationStatusWithAcceptTime provides a mock function with given fields: ctx, invitationID, status, acceptedAt
func (_m *Database) UpdateInvitationStatusWithAcceptTime(ctx context.Context, invitationID string, status string, acceptedAt time.Time) error {
	ret := _m.Called(ctx, invitationID, status, acceptedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInvitationStatusWithAcceptTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, invitationID, status, acceptedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMembership provides a mock function with given fields: ctx, membership
func (_m *Database) UpdateMembership(ctx context.Context, membership *ydb.Membership) error {
	ret := _m.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMembership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Membership) error); ok {
		r0 = rf(ctx, membership)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrganization provides a mock function with given fields: ctx, org
func (_m *Database) UpdateOrganization(ctx context.Context, org *ydb.Organization) error {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Organization) error); ok {
		r0 = rf(ctx, org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSubscription provides a mock function with given fields: ctx, subscription
func (_m *Database) UpdateSubscription(ctx context.Context, subscription *ydb.Subscription) error {
	ret := _m.Called(ctx, subscription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Subscription) error); ok {
		r0 = rf(ctx, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *Database) UpdateUser(ctx context.Context, user *ydb.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserPassword provides a mock function with given fields: ctx, userID, passwordHash
func (_m *Database) UpdateUserPassword(ctx context.Context, userID string, passwordHash string) error {
	ret := _m.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserPasswordResetInfo provides a mock function with given fields: ctx, userID, code, expiresAt
func (_m *Database) UpdateUserPasswordResetInfo(ctx context.Context, userID string, code string, expiresAt time.Time) error {
	ret := _m.Called(ctx, userID, code, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPasswordResetInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, userID, code, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVideo provides a mock function with given fields: ctx, video
func (_m *Database) UpdateVideo(ctx context.Context, video *ydb.Video) error {
	ret := _m.Called(ctx, video)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ydb.Video) error); ok {
		r0 = rf(ctx, video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVideoStatus provides a mock function with given fields: ctx, videoID, status, publicURL
func (_m *Database) UpdateVideoStatus(ctx context.Context, videoID string, status string, publicURL string) error {
	ret := _m.Called(ctx, videoID, status, publicURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVideoStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, videoID, status, publicURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
